site_name: ReadMe 软件学院互助文档

nav:
  - 首页:
    - 欢迎: "index.md"
    - 致作者: "ToAuthor.md"
    - 致读者: "ToReader.md"
    - 志愿工时发放标准: "ReadMe志愿工时发放标准.md"
  - 课程笔记: 
    - 介绍: "note/note.md"
    - 操作系统复习提纲: "note/os/os.md"
    - 人工智能导论:
      - Learning(1): "note/AI-learning1/AI-learning1.md"
    - 其他: "note/other.md"
  - 作业攻略: 
    - 介绍: "homework/homework.md"
    - 数据结构OJ较难作业解析:
      - By 作者: "homework/dsa-OJ/README.md"
      - OJ1-3_灯塔_归并排序: "homework/dsa-OJ/OJ1/OJ1-3.md"
      - OJ2-3_游戏_括号匹配: "homework/dsa-OJ/OJ2/OJ2-3.md"
      - OJ3-2_旅行商_拓扑排序: "homework/dsa-OJ/OJ3/OJ3-2.md"
      - OJ3-3_气象台_KD树: "homework/dsa-OJ/OJ3/OJ3-3.md"
    - 其他: "homework/other.md"
  - 技术分享: 
    - 介绍: "tech/tech.md"
    - JS语法糖及语法坑: "tech/JavaScript语法糖及语法坑.md"
    - Manjaro系统入门: "tech/Intro-To-Manjaro/ManjaroIntro.md"
    - 油猴脚本: "tech/monkey_script/MonkeyScript.md"
    - 2022年暑培资料:
      - 前端基础: "tech/2022Summer/frontend-base.md"
      - Vue.js: "tech/2022Summer/Vue/vue.md"
      - Node.js: "tech/2022Summer/Nodejs/Nodejs.md"
      - Flask: "tech/2022Summer/flask.md"
    - 其他: "tech/other.md"

theme:
  name: material
  icon:
    logo: material/file-document
  palette: 
    primary: teal
  language: zh
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/ssast-readme/ssast-readme.github.io'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/squidfunk'
    - icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/in/squidfunk'


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
