site_name: ReadMe 软件学院互助文档

nav:
  - 首页:
    - 欢迎: "index.md"
    - 致作者: "ToAuthor.md"
    - 致读者: "ToReader.md"
    - 志愿工时发放标准: "ReadMe志愿工时发放标准.md"
  - 课程笔记: 
    - 介绍: "note/note.md"
    - 操作系统:
      - 复习提纲: "note/os/os.md"
    - 人工智能导论:
      - Learning(1): "note/AI-learning1/AI-learning1.md"
    - 复变函数引论: 
      - 杨晓京老师笔记: "note/complex-function/readme.md"
    - 数据库: 
      - 第六章E-R模型: "note/database/Chapter6/Chapter 6  Database Design Using the E-R Model.md"
      - 第七章关系数据库设计: "note/database/Chapter7/Chapter 7.md"
    - 其他: "note/other.md"
  - 作业攻略: 
    - 介绍: "homework/homework.md"
    - 数据结构OJ较难作业解析:
      - By 作者: "homework/dsa-OJ/README.md"
      - OJ1-3_灯塔_归并排序: "homework/dsa-OJ/OJ1/OJ1-3.md"
      - OJ2-3_游戏_括号匹配: "homework/dsa-OJ/OJ2/OJ2-3.md"
      - OJ3-2_旅行商_拓扑排序: "homework/dsa-OJ/OJ3/OJ3-2.md"
      - OJ3-3_气象台_KD树: "homework/dsa-OJ/OJ3/OJ3-3.md"
    - 操作系统:
      - 在xv6中实现音频播放: "homework/OS-music/content.md"
    - 汇编与编译原理:
      - VS2022配置汇编高亮: "homework/VS-Assembly/VS-Assembly.md"
    - Qt小学期: 
      - FFmpeg与视频编解码: "homework/Qt/FFmpeg.md"
    - 其他: "homework/other.md"
  - 技术分享: 
    - 介绍: "tech/tech.md"
    - JS语法糖及语法坑: "tech/JavaScript语法糖及语法坑.md"
    - Manjaro系统入门: "tech/Intro-To-Manjaro/ManjaroIntro.md"
    - 油猴脚本: "tech/monkey_script/MonkeyScript.md"
    - 连接Tsinghua-Secure: "tech/Tsinghua-Secure/tsinghua-secure.md"
    - 在软工项目中使用SSL证书: "tech/using-SSL-in-SE/content.md"
    - 合法的、安全地发布自己的网站: "tech/publish_website/How-to-publish-your-website.md"
    - Python爬虫框架Scrapy: "tech/Scrapy/Scrapy.md"
    - Zerotier实现内网穿透: "tech/Zerotier/Zerotier_guide.md"
    - apache2简易指北: "tech/apache2/apache2_guide.md"
    - 2022年暑培资料:
      - 前端基础: "tech/2022Summer/frontend-base.md"
      - Vue.js: "tech/2022Summer/Vue/vue.md"
      - Node.js: "tech/2022Summer/Nodejs/Nodejs.md"
      - Flask: "tech/2022Summer/flask.md"
      - Webpack: "tech/2022Summer/webpack/webpack.md"
      - Linux: "tech/2022Summer/Linux.md"
      - Python: "tech/2022Summer/Python/python.md"
      - Git: "tech/2022Summer/git/git.md"
      - CMake: "tech/2022Summer/cmake/cmake.md"
      - Qt: "tech/2022Summer/Qt/qt.md"
      - Docker: "tech/2022Summer/docker/Docker_Tutorial.md"
      - 基于uni-app框架的小程序开发: "tech/2022Summer/uni-app/基于uni-app框架的小程序开发.md"
    - 其他: "tech/other.md"
  - 科创经验分享:
    - 星火计划: 
      - 经验分享: "innovation/star/share.md"
  - 书信传情: 
    - 简介: "letter/ReadMe X 书信传情2021简介.md"
    - 2021:
      - 经历&建议: "letter/2021书信传情-经历&建议.md"
      - 心态调整: "letter/2021书信传情-心态调整.md"
      - 信息获取: "letter/2021书信传情-信息获取.md"
      - 学业规划: "letter/2021书信传情-学业规划.md"
      - 未来展望: "letter/2021书信传情-未来展望.md"

theme:
  name: material
  icon:
    logo: material/file-document
  palette: 
    primary: teal
  language: zh
  features:
    - navigation.instant
    - navigation.tabs
    - navigation
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/ssast-readme/ssast-readme.github.io'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/squidfunk'
    - icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/in/squidfunk'


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
